# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=/Users/bergman/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="random"
ZSH_THEME_RANDOM_CANDIDATES=(

  "crunch"
  "half-life"
  "geoffgarside"
  "wedisagree"
  "eastwood"
  "theunraveler"
  "steeef"
  "linuxonly"
  "pygmalion"
  "maran"
  
  
  
  "fishy"
  "af-magic"
  
  
  "fletcherm"
  "zhann"
  "arrow"
  "skaro"
  "mh"
  "garyblessington"
  "norm"
  "alanpeabody"
  "avit"
  "candy"
  "dieter"
  "dogenpunk"
  "wezm"
  "mira"
  "frisk"
  "duellj"
  "junkfood"
  "intheloop"
  "avit"
  "gnzh"
  "bureau"
  "mikeh"
  "flazz"
  "garyblessington"
  "norm"
  "cloud"
  "dpoggi"
  "fishy"
  "jbergantine"
  "kolo"
  "nanotech"
  "peepcode"
  "smt"
  "suvash"
  "superjarin"
  "skaro"
  "sporty_256"
  "theunraveler"
  "terminalparty"
  "wedisagree"
  "xiong-chiamiov"  
)


# Set list of themes to load
# Setting this variable when ZSH_THEME=random
# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# autojump
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

#nvm
  # export NVM_DIR="$HOME/.nvm"
  # . "/usr/local/opt/nvm/nvm.sh"

#杭锋提供了cnpm
alias cnpm="npm --registry=https://registry.npm.taobao.org \
  --disturl=https://npm.taobao.org/dist"




#设置ruby

export PATH="/usr/local/opt/ruby/bin:$PATH"
# For compilers to find ruby you may need to set:
export LDFLAGS="-L/usr/local/opt/ruby/lib"
export CPPFLAGS="-I/usr/local/opt/ruby/include"
# For pkg-config to find ruby you may need to set:
export PKG_CONFIG_PATH="/usr/local/opt/ruby/lib/pkgconfig"


# 太牛了 anaconda直接改了bash的配置, 但是他没有改zsh的
# added by Anaconda3 2019.10 installer
# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
#__conda_setup="$(CONDA_REPORT_ERRORS=false '/Users/bergman/git/malgo/anaconda3/bin/conda' shell.bash hook 2> /dev/null)"
#if [ $? -eq 0 ]; then
#    \eval "$__conda_setup"
#else
#    if [ -f "/Users/bergman/git/malgo/anaconda3/etc/profile.d/conda.sh" ]; then
#        . "/Users/bergman/git/malgo/anaconda3/etc/profile.d/conda.sh"
#        CONDA_CHANGEPS1=false conda activate base
#    else
#        \export PATH="/Users/bergman/git/malgo/anaconda3/bin:$PATH"
#    fi
#fi
#unset __conda_setup
# <<< conda init <<<
#export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.ustc.edu.cn/homebrew-bottles

#export http_proxy=http://127.0.0.1:1087;
#export https_proxy=http://127.0.0.1:1087;

alias neton="export all_proxy=socks5://127.0.0.1:1080"
alias netoff="unset all_proxy"
alias ip="curl cip.cc"

#github加代理, 这个是http模式, 对我没用.
#alias giton="git config --global http.https://github.com.proxy 'socks5://127.0.0.1:1080'"

#取消代理
#alias gitoff="git config --global --unset http.https://github.com.proxy"


alias pip3="pip3 --proxy 127.0.0.1:1087"
alias pip="pip --proxy 127.0.0.1:1087"
